const DATA = [
  {
    id: 0,
    title: "iPhone 11",
    price: 749,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam minima rem cupiditate. Laudantium delectus fuga et vel debitis. Ducimus facilis fugiat nihil corporis nam dolorem, ratione asperiores fuga beatae sit.",
    img: "assets/images/products/iphone11.jpg",
    category: "iphone",
  },
  {
    id: 1,
    title: "iPhone 12",
    price: 949,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam minima rem cupiditate. Laudantium delectus fuga et vel debitis. Ducimus facilis fugiat nihil corporis nam dolorem, ratione asperiores fuga beatae sit.",
    img: "assets/images/products/iphone12.jpg",
    category: "iphone",
  },
  {
    id: 2,
    title: "iPhone 13",
    price: 999,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam minima rem cupiditate. Laudantium delectus fuga et vel debitis. Ducimus facilis fugiat nihil corporis nam dolorem, ratione asperiores fuga beatae sit.",
    img: "assets/images/products/iphone13beige.jpg",

    category: "iphone",
  },
  {
    id: 3,
    title: "iPhone 13",
    price: 999,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam minima rem cupiditate. Laudantium delectus fuga et vel debitis. Ducimus facilis fugiat nihil corporis nam dolorem, ratione asperiores fuga beatae sit.",
    img: "assets/images/products/iphone13green.jpg",
    category: "iphone",
  },
  {
    id: 4,
    title: "iPhone 13 pro max",
    price: 1259,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam minima rem cupiditate. Laudantium delectus fuga et vel debitis. Ducimus facilis fugiat nihil corporis nam dolorem, ratione asperiores fuga beatae sit.",
    img: "assets/images/products/iphone13promax.jpg",
    category: "iphone",
  },
  {
    id: 5,
    title: "iPhone 13",
    price: 1059,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam minima rem cupiditate. Laudantium delectus fuga et vel debitis. Ducimus facilis fugiat nihil corporis nam dolorem, ratione asperiores fuga beatae sit.",
    img: "assets/images/products/iphone13red.jpg",
    category: "iphone",
  },
  {
    id: 6,
    title: "iPhone 12",
    price: 959,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam minima rem cupiditate. Laudantium delectus fuga et vel debitis. Ducimus facilis fugiat nihil corporis nam dolorem, ratione asperiores fuga beatae sit.",
    img: "assets/images/products/iphone12green.jpg",
    category: "iphone",
  },
  {
    id: 7,
    title: "iPhone 13 pro max",
    price: 1199,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam minima rem cupiditate. Laudantium delectus fuga et vel debitis. Ducimus facilis fugiat nihil corporis nam dolorem, ratione asperiores fuga beatae sit.",
    img: "assets/images/products/iphone13promaxgold.jpg",
    category: "iphone",
  },
  {
    id: 8,
    title: 'MacBook Air 13"',
    price: 1159,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam minima rem cupiditate. Laudantium delectus fuga et vel debitis. Ducimus facilis fugiat nihil corporis nam dolorem, ratione asperiores fuga beatae sit.",
    img: "assets/images/products/macbookair.jpg",
    category: "macbook",
  },
  {
    id: 9,
    title: 'MacBook Pro 16"',
    price: 4499,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam minima rem cupiditate. Laudantium delectus fuga et vel debitis. Ducimus facilis fugiat nihil corporis nam dolorem, ratione asperiores fuga beatae sit.",
    img: "assets/images/products/mbp16.jpg",
    category: "macbook",
  },
  {
    id: 10,
    title: 'MacBook Pro 16"',
    price: 3999,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam minima rem cupiditate. Laudantium delectus fuga et vel debitis. Ducimus facilis fugiat nihil corporis nam dolorem, ratione asperiores fuga beatae sit.",
    img: "assets/images/products/mbp16m1.jpg",
    category: "macbook",
  },
  {
    id: 11,
    title: 'MacBook Air 13" m1',
    price: 2759,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam minima rem cupiditate. Laudantium delectus fuga et vel debitis. Ducimus facilis fugiat nihil corporis nam dolorem, ratione asperiores fuga beatae sit.",
    img: "assets/images/products/mba.jpg",
    category: "macbook",
  },
  {
    id: 12,
    title: "Watch Series 7 45mm Blue",
    price: 699,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam minima rem cupiditate. Laudantium delectus fuga et vel debitis. Ducimus facilis fugiat nihil corporis nam dolorem, ratione asperiores fuga beatae sit.",
    img: "assets/images/products/watch7.jpg",
    category: "watch",
  },
  {
    id: 13,
    title: "Watch Series 5 40mm Silver",
    price: 659,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam minima rem cupiditate. Laudantium delectus fuga et vel debitis. Ducimus facilis fugiat nihil corporis nam dolorem, ratione asperiores fuga beatae sit.",
    img: "assets/images/products/watch5.jpg",
    category: "watch",
  },
  {
    id: 14,
    title: "Watch Series 7 45mm Green",
    price: 599,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam minima rem cupiditate. Laudantium delectus fuga et vel debitis. Ducimus facilis fugiat nihil corporis nam dolorem, ratione asperiores fuga beatae sit.",
    img: "assets/images/products/watch7green.jpg",
    category: "watch",
  },
  {
    id: 15,
    title: "Watch SE 40mm Gold Aluminium",
    price: 459,
    desc: "Lorem ipsum dolor sit amet consectetur adipisicing elit. Aperiam minima rem cupiditate. Laudantium delectus fuga et vel debitis. Ducimus facilis fugiat nihil corporis nam dolorem, ratione asperiores fuga beatae sit.",
    img: "assets/images/products/watchse.jpg",
    category: "watch",
  },
];

export default DATA;
